### ISSUE TITLE
validateOnSave and formatting

### ISSUE THREAD

**Issue by Vermyndax** [sublimelsp/LSP-terraform#23]
I must be missing something, but what do I need to enable in settings to turn on validateOnSave and formatting (terraform fmt) functionality? I have the CLI installed, but it is not engaging anything when I save the file in ST.

**Comment by rchl** [comment]
I've added info about formatting to the readme: https://github.com/sublimelsp/LSP-terraform#formatting

As far as `validateOnSave`, you probably don't want to use that since that seem like an inferior way of validating (normally it happens on just opening or changing the file) but there is an option for that in the package settings.

**Comment by rchl** [comment]
Note that I didn't have too much luck with formatting on save with this server due to it being fairly slow in performing the formatting and which results in the save action timing out since the LSP package has a budget of 2s in which the server has to fit.

Though the budget of 2s is configurable using the `on_save_task_timeout_ms` LSP setting so you can bump it if you want. Just be aware that the file will not be saved until the server is done formatting or the save action times out.
