### ISSUE TITLE
Syntax matching

### ISSUE THREAD

**Issue by justaskz** [sublimelsp/LSP-terraform#26]
I have installed [LSP](https://packagecontrol.io/packages/LSP), [LSP-terraform](https://packagecontrol.io/packages/LSP-terraform) and [Terraform Syntax](https://packagecontrol.io/packages/Terraform) as stated in README file.

The problem is that if I open `*.hcl` file, it gets syntax set as Terraform, which is ok, because I get syntax highlighting. The unwanted side effect of this that LSP-Terraform also starts and marks majority of the file as invalid Terraform syntax. Which is true, because it is HCL. How to update the config that LSP-Terraform will start only for `*.tf` files?

**Comment by rchl** [comment]
LSP triggers based on syntax `scope` which is [the same for both .tf and .hcl](https://github.com/alexlouden/Terraform.tmLanguage/blob/7faec10b4057b95bff82fb585730e560871d26c4/Terraform.sublime-syntax#L25-L28C8) so I don't really see a way of fixing that.

@radeksimko should the syntax maybe not declare support for .hcl? It doesn't seem like in vscode the syntax or the server [triggers for .hcl files](https://github.com/hashicorp/vscode-terraform/blob/101d69e5db4ed6d064ae39f440bb98d5ffe6c6bf/package.json#L52-L53).

**Comment by radeksimko** [comment]
In terms of _highlighting_, it _may_ be fine to treat all HCL-based languages the same (`*.tf`, `*.tfvars`, `*.hcl`). The question is of course how the grammar was written. Right now AFAICT the grammar is Terraform specific, so it's not really the right choice for any HCL other than Terraform and for the same reason it may not even be the right choice for `*.tfvars`. That said, it's probably a reasonable/pragmatic choice in lack of better options.

https://github.com/alexlouden/Terraform.tmLanguage/blob/7faec10b4057b95bff82fb585730e560871d26c4/Terraform.sublime-syntax#L69

For any other purposes, especially language server powered features, these should _never_ be treated the same. We maintain our own [HCL grammar](https://github.com/hashicorp/syntax/blob/main/syntaxes/hcl.tmGrammar.json) and HCL extension for VS Code, which are separate from [Terraform syntax](https://github.com/hashicorp/syntax/blob/main/syntaxes/terraform.tmGrammar.json) because those are different languages. The [HCL extension](https://github.com/hashicorp/vscode-hcl) doesn't do anything other than highlighting and it does not come with a language server.

We also document this [here](https://github.com/hashicorp/terraform-ls/blob/main/docs/language-clients.md#language-ids):

> The following file types are currently supported and language IDs expected:
> 
> `terraform` - standard `*.tf` config files
> `terraform-vars` - variable files (`*.tfvars`)
> 
> Client can choose to highlight other files locally, but such other files must not be send to the server as the server isn't equipped to handle those.
> 
> Clients specifically should not send *.tf.json, *.tfvars.json nor Packer HCL config nor any other HCL config files as the server is not equipped to handle these file types.

It looks like we also touched on this topic some time ago in https://github.com/alexlouden/Terraform.tmLanguage/issues/48

On somewhat positive side, it's on my near term plan to switch GitHub linguist to our TextMate grammar I linked above, which would at least solve the duplication problem as the repo could potentially remove the TextMate files and focus purely on Sublime Text syntax.

I'm not sure if the problem we're discussing here with scopes is easier to solve in ST syntax, compared to TM, but I thought I'd mention it anyway.

**Comment by rchl** [comment]
Thanks for that explanation.
In that case it sounds like it might be a good idea to remove `.hcl` extension from the list of supported extension by the terraform syntax. If someone would really want to still use it for those files then it's possibly to manually assign it for that extension.

Alternatively, as also mentioned in the linked discussion, we could add a separate syntax file for `.hcl` with different scope and make it just include the main syntax. This approach should be backwards compatible.

**Comment by rchl** [comment]
This is not fixed in https://packagecontrol.io/packages/Terraform by assigning a different scope to `.hcl` extension.
