### ISSUE TITLE
Please publish this package to packagecontrol

### ISSUE THREAD

**Issue by mconigliaro** [sublimelsp/LSP-terraform#5]
Related: https://github.com/sublimelsp/LSP/pull/1861

**Comment by rchl** [comment]
I suppose the idea was to handle #4 first but it's unclear when someone will have time to do it.

**Comment by radeksimko** [comment]
Is it worth linking to the package from the Readme and/or the repo description also?
https://packagecontrol.io/packages/LSP-Terraform

**Comment by rchl** [comment]
Including a link to the package from its readme seems redundant because then it would be linking to itself when looking at it from packagecontrol.io.

But ST packages typically include installation instructions that say that you should install the package from Package Control (see https://github.com/sublimelsp/LSP-eslint/ for example) and I think we should add that.
